import os

class ASSGenerator:
    def __init__(self, font_name="Arial", font_size=20, primary_color="&H00FFFFFF", highlight_color="&H0000FFFF"):
        """
        初始化 ASS 字幕生成器
        :param font_name: 字体名称 (需系统中存在)
        :param font_size: 字体大小
        :param primary_color: 普通文字颜色 (ASS Hex: &HAABBGGRR) - 默认白色
        :param highlight_color: 高亮文字颜色 - 默认黄色 (&H0000FFFF -> Yellow in BGR)
        """
        self.font_name = font_name
        self.font_size = font_size
        self.primary_color = primary_color
        self.highlight_color = highlight_color
        
    def generate_ass(self, segments, output_path):
        """
        根据 Whisper segments 生成 ASS 文件
        :param segments: Whisper result['segments']，必须包含 'words' 字段
        :param output_path: 输出 .ass 文件路径
        """
        header = self._get_header()
        events = self._generate_events(segments)
        
        with open(output_path, 'w', encoding='utf-8-sig') as f:
            f.write(header)
            f.write("\n".join(events))
            
        return output_path

    def _get_header(self):
        return f"""[Script Info]
; Script generated by AutoSubtitles AI
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{self.font_name},{self.font_size},{self.primary_color},&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.5,0,2,10,10,20,1
Style: Highlight,{self.font_name},{self.font_size + 4},{self.highlight_color},&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.5,0,2,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    def _generate_events(self, segments):
        events = []
        for seg in segments:
            if 'words' not in seg:
                # Fallback if no word timestamps
                start = self._format_time(seg['start'])
                end = self._format_time(seg['end'])
                text = seg['text'].strip()
                events.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")
                continue

            words = seg['words']
            # Hormozi Style: Show the whole sentence (or chunk), but highlight words one by one.
            # 为了避免屏幕文字太多，如果 segment 太长，可以不切分，或者假设 Whisper 已经切分好了。
            # 策略：对于这个 segment 的每一段时间（对应一个 word），生成一行 Dialogue。
            # 这行 Dialogue 显示整个 segment 的文本，但当前 word 用 Highlight 样式 (或颜色代码)。
            
            # 更好的策略：逐词显示？不，Hormozi 风格通常是一小段话都在，当前词变色/变大。
            
            # 构建整句的文本结构
            # 这种方式会产生大量重叠的事件，需要确保 Layer 正确或者时间不重叠。
            # 简单起见，我们把时间切分为 word 的时间段。
            # 在 word[i] 的时间段内，显示整个句子，其中 word[i] 高亮。
            
            full_text_words = [w['word'].strip() for w in words]
            
            # 如果句子太长，可能需要切分显示。这里假设 Whisper 的 segment 长度适中。
            
            for i, word in enumerate(words):
                w_start = word['start']
                w_end = word['end']
                
                # 填补空隙：如果 word[i] 和 word[i+1] 之间有空隙，也需要显示（通常显示上一个状态或全白）
                # 简单起见，让当前 word 的高亮持续到下一个 word 开始，或者 segment 结束。
                
                next_start = words[i+1]['start'] if i < len(words) - 1 else seg['end']
                # 实际上 word['end'] 可能小于 next_start。这段时间保持高亮或者恢复？
                # 通常保持高亮直到下一个词开始比较流畅。
                display_end = next_start
                
                ass_start = self._format_time(w_start)
                ass_end = self._format_time(display_end)
                
                # 构建文本：当前词前后加上样式标签
                # { \rHighlight } Word { \rDefault }
                # \rStyle 重置为指定样式
                
                line_parts = []
                for j, w_text in enumerate(full_text_words):
                    if i == j:
                        # 当前词：放大+变色
                        # 使用 {\rHighlight} 标签
                        line_parts.append(f"{{\\rHighlight}}{w_text}{{\\rDefault}}")
                    else:
                        line_parts.append(w_text)
                
                final_text = " ".join(line_parts)
                events.append(f"Dialogue: 0,{ass_start},{ass_end},Default,,0,0,0,,{final_text}")

        return events

    def _format_time(self, seconds):
        """Format time for ASS: H:MM:SS.cs"""
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int((seconds - int(seconds)) * 100) # centiseconds
        return f"{h}:{m:02d}:{s:02d}.{cs:02d}"
